waseefakhtar/dose-android

- .github/workflows/android.yml
- Add run test flow to CI pipeline
- Add gradle caching for faster consecutive builds
Issue: https://github.com/waseefakhtar/dose-android/issues/10
> Add run tests to ci pipeline

- app/build.gradle
- app/google-services.json
- build.gradle
- settings.gradle
> Feature: Setup Firebase, add Firebase Analytics & Crashlytics

- .idea/.gitignore
- app/build.gradle
- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/calendar/viewmodel/CalendarState.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/calendar/viewmodel/CalendarViewModel.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/viewmodel/MedicationConfirmState.kt
Closes #28 
Here is my idea and implementation for a ViewModel layer in the dose app.
There is some additional implementations and patterns I can add to this to make it sturdier, but I want to get feedback on this initial draft first.
> Feature: Setup basic ViewModel layer with State classes

- .gitignore
- app/src/main/java/com/waseefakhtar/doseapp/data/MedicationDao.kt
- app/src/main/java/com/waseefakhtar/doseapp/data/repository/MedicationRepositoryImpl.kt
- app/src/main/java/com/waseefakhtar/doseapp/domain/repository/MedicationRepository.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/MedicationConfirmRoute.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/usecase/AddMedicationUseCase.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/viewmodel/MedicationConfirmViewModel.kt
Complete issue : 
Show a success message (use Toast or Snackbar) when new Medication is added to DB succesfully. #31
@waseefakhtar
> Add toast when success insert new medication to DB

- .idea/kotlinc.xml
- app/build.gradle
- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
- build.gradle
Bump compileSdk to 33
Bump compose-ui to 1.4.0-rc01
Bump kotlin to 1.8.10
Bump navigation to 2.5.3
Bump hilt to 2.45
Bump material3 to 1.1.0-beta01
Bump lifecycle-runtime to 2.6.0
Bump activity-compose to 1.6.1
> Bump compileSdk, compose-compiler, kotlin, navigation, hilt, room, core, material3, lifecycle-runtime, activity-compose

- app/src/main/java/com/waseefakhtar/doseapp/data/MedicationDao.kt
- app/src/main/java/com/waseefakhtar/doseapp/data/entity/MedicationEntity.kt
- app/src/main/java/com/waseefakhtar/doseapp/data/mapper/MedicationMapper.kt
- app/src/main/java/com/waseefakhtar/doseapp/data/repository/MedicationRepositoryImpl.kt
- app/src/main/java/com/waseefakhtar/doseapp/domain/model/Medication.kt
- app/src/main/java/com/waseefakhtar/doseapp/domain/repository/MedicationRepository.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/usecase/UpdateMedicationUseCase.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/viewmodel/HomeViewModel.kt
> Feature: Update medication on completed and show complete status in Home

- app/src/main/java/com/waseefakhtar/doseapp/data/entity/MedicationEntity.kt
- app/src/main/java/com/waseefakhtar/doseapp/data/mapper/MedicationMapper.kt
- app/src/main/java/com/waseefakhtar/doseapp/data/repository/MedicationRepositoryImpl.kt
- app/src/main/java/com/waseefakhtar/doseapp/domain/model/Medication.kt
- app/src/main/java/com/waseefakhtar/doseapp/domain/repository/MedicationRepository.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/navigation/AddMedicationDestination.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/viewmodel/AddMedicationViewModel.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/MedicationConfirmRoute.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/navigation/MedicationConfirmDestination.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/usecase/AddMedicationUseCase.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/viewmodel/MedicationConfirmState.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/viewmodel/MedicationConfirmViewModel.kt
- app/src/main/java/com/waseefakhtar/doseapp/navigation/DoseNavHost.kt
> Add Medications separately for each recurrence and time of day

- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/viewmodel/AddMedicationViewModel.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
- app/src/main/java/com/waseefakhtar/doseapp/util/TimeUtils.kt
- app/src/main/res/values/strings.xml
- build.gradle
> Show time remaining for each medication

- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
> Group HomeScreen medications by Today, This Week, and Next Week

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/waseefakhtar/doseapp/App.kt
- app/src/main/java/com/waseefakhtar/doseapp/MainActivity.kt
- app/src/main/java/com/waseefakhtar/doseapp/MedicationNotificationReceiver.kt
- app/src/main/java/com/waseefakhtar/doseapp/MedicationNotificationService.kt
- app/src/main/java/com/waseefakhtar/doseapp/NotificationActionReceiver.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/navigation/HomeDestination.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/MedicationConfirmRoute.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/navigation/MedicationConfirmDestination.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/viewmodel/MedicationConfirmViewModel.kt
- app/src/main/java/com/waseefakhtar/doseapp/navigation/DoseNavHost.kt
- app/src/main/res/drawable/ic_dose.xml
- gradle/wrapper/gradle-wrapper.properties
> Feature: Medication Notification

- app/src/main/java/com/waseefakhtar/doseapp/DoseApp.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/navigation/HomeDestination.kt
1. Hide bottom bar temporarily.
2. Add empty card to show when there are no medications added.
3. Add `onClick` functionality of Empty and DailyOverview card to navigate to Add Medication screen.
> UI/UX: Cleanup

- app/src/main/java/com/waseefakhtar/doseapp/DoseApp.kt
- app/src/main/java/com/waseefakhtar/doseapp/MainActivity.kt
- app/src/main/java/com/waseefakhtar/doseapp/MedicationNotificationReceiver.kt
- app/src/main/java/com/waseefakhtar/doseapp/analytics/AnalyticsEvents.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationconfirm/MedicationConfirmRoute.kt
> Tracking & UI/UX: Add an event to track when app is opened from a reminder notification, improve padding, texts

- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
> Fix recurrence dropdown menu

- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
Link to the issue :- https://github.com/waseefakhtar/dose-android/issues/81
> Bugfix/add medication screen UI fix

- app/src/main/java/com/waseefakhtar/doseapp/feature/addmedication/AddMedicationRoute.kt
> Feature: Add support to delete additional time in AddMedication

- app/build.gradle
- build.gradle
> Migrated Room to KSP

- app/src/main/java/com/waseefakhtar/doseapp/analytics/AnalyticsEvents.kt
- app/src/main/java/com/waseefakhtar/doseapp/extension/DateExtension.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/HomeScreen.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/data/CalendarDataSource.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/model/CalendarModel.kt
- app/src/main/res/values/strings.xml
> Feature: Calendar header in Home

- app/src/main/res/values/strings.xml
Now we can add new medications :D
Solves #140
> Fix, closes #140

- .github/workflows/android.yml
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/viewmodel/HomeState.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/home/viewmodel/HomeViewModel.kt
Using StateFlow instead of mutableStateOf to:
1. Combines all state updates into a single stream
2. Provides a proper initial value
3. Removes the need for separate state management
```
Unparseable date: ""
2025-01-04 22:28:58.427  6077-6077  System.err              com.waseefakhtar.doseapp             W  	at java.text.DateFormat.parse(DateFormat.java:389)
2025-01-04 22:28:58.427  6077-6077  System.err              com.waseefakhtar.doseapp             W  	at com.waseefakhtar.doseapp.extension.DateExtensionKt.toDate(DateExtension.kt:26)
2025-01-04 22:28:58.427  6077-6077  System.err              com.waseefakhtar.doseapp             W  	at com.waseefakhtar.doseapp.feature.home.data.CalendarDataSource.getLastSelectedDate(CalendarDataSource.kt:17)
2025-01-04 22:28:58.427  6077-6077 …
```
> Fix parsing empty lastSelectedDate

- app/src/main/java/com/waseefakhtar/doseapp/feature/home/MedicationCard.kt
- app/src/main/java/com/waseefakhtar/doseapp/feature/medicationdetail/MedicationDetailRoute.kt
- app/src/main/java/com/waseefakhtar/doseapp/util/MedicationType.kt
> UI: Show medication type as icon for each medication in Home and MedicationDetail
